=== josanuz/ThreatDetector/Resources/Event.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Event",
    "description": "Events Generated by the clients",
    "type": "object",
    "properties": {
        "originIp": {
            "description": "Packet Origin IP",
            "type": "string"
        },
        "destinationIP": {
            "description": "Packet Destination IP",
            "type": "string"
        },
        "headers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "headerName": {
                        "type": "string"
                    },
                    "headerValue": {
                        "type": "string"
                    }
                }
            }
        },
        "protocol": {
            "description": "HTTP | POP3 | IMAP",
            "type": "string"
        },
        "length": {
            "description": "Content Lenght",
            "type": "integer",
            "inclusiveMinimum": 0
        },
        "content": {
            "description": "El contenido del mensaje",
            "type": "object",
            "properties": {
                "messageType": {
                    "description": "Mail | HTTP Request| HTTP Request",
                    "type": "string"
                },
                "content": {
                    "description": "The Message Content Check Wiky",
                    "type": "string"
                }
            }
        },
        "required" : ["orginIp", "headers", "destinationIP", "protocol", "lenght", "content"]
    }
}

=== josanuz/ThreatDetector/Resources/ejemplo.evento.json
{
    "originIp": "127.0.0.1",
    "destinationIP": "127.0.0.1",
    "headers": [
        {
            "headerName": "Accept",
            "headerValue": "application/json"
        },
        {
            "headerName": "Content Type",
            "headerValue": "application/json"
        },
        {
            "headerName": "User Agent",
            "headerValue": "SpringTestJUnit/CURL"
        },
        {
            "headerName": "Forwarder",
            "headerValue": "0.0.0.0"
        },
        {
            "headerName": "Host",
            "headerValue": "Local Host"
        }
    ],
    "protocol": "HTTP",
    "length": 512,
    "content": {
        "messageType": "HTTP Request",
        "content": "GET /api/messages?url=SELECT%20*%20FROM%20USER%20WHERE%20TRUE%3B"
    }
}
